import type { Metadata } from "next";
import { Merriweather } from "next/font/google";
import Header from "../components/Header";
import Footer from "../components/Footer";
import "./globals.css";;

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const merriweather = Merriweather({
  subsets: ["latin"],   
  weight: ["400", "700", "900"], 
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
     
        className={`${merriweather.className} antialiased`}
      >
         <Header />
        {children}
        <Footer/>
      </body>
    </html>
  );
}


