import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import { Merriweather } from "next/font/google";
import Header from "../components/Header";
import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



const merriweather = Merriweather({
  subsets: ["latin"],   
  weight: ["400", "700", "900"], 
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
     
        className={`${merriweather.className} antialiased`}
      >
         <Header />
        {children}
      </body>
    </html>
  );
}


